### ISSUE TITLE
Themenvorschläge auf unserer Seite sammeln/integrieren

### ISSUE THREAD

**Issue by janedde** [barcamperfurt/barcamperfurt#14]
Pete sagte im Call was von Google....... ?

**Comment by cainvommars** [comment]
aktuelle implementierung sieht so aus, ich packe das jetzt live, das sieht aber nur jemand der die adresse kennt, es ist noch nicht im header verlinkt 
<img width="762" alt="bildschirmfoto 2015-09-13 um 13 23 35" src="https://cloud.githubusercontent.com/assets/185672/9836443/ac894628-5a1a-11e5-9724-84889c2855bd.png">

vom wording her muss klar sein das die sessionpitches erst am camp tag stattfinden, da wollte @saschawech den text anpassen

wie integrieren wir da session wünsche (wenn wir das überhaupt wollen? vielleicht generell was 2-spaltiges? cc @PushSomePixels

**Comment by cainvommars** [comment]
done und live :)
