### ISSUE TITLE
Nach Eintragen in Google Forms ein "zurück zur Übersicht"-Link

### ISSUE THREAD

**Issue by saschawech** [barcamperfurt/barcamperfurt#16]
Nach dem Eintragen einer Session möchte ich zurück zur ursprünglichen Seite (/sessions)

Alternativ einen Hinweis, dass ich das Fenster jetzt schließen kann (da Google Forms in neuem Tab öffnet)

**Comment by cainvommars** [comment]
wirds nicht geben, wir haben keine chance google da zu beeinflussen
